
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=my_api_rest
      - POSTGRES_USER=martin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./SQL_init:/docker-entrypoint-initdb.d/
    networks:
      - postgres_network
    ports:
      - "5433:5432"
      
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  api:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https:/https
    depends_on:
      - postgres
      - redis
    networks:
      - postgres_network
      - redis_network
  
volumes:
  postgres_data:
  redis_data:

networks:
  postgres_network:
  redis_network:
